apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: enterprise-angular-seed
  description: Angular CLI–based seed application maintained by Infosys, incorporating enterprise-ready best practices.
  annotations:
    github.com/project-slug: Infosys/enterprise-angular-seed
    backstage.io/techdocs-ref: dir:.
  tags: [angular, enterprise, seed, template]
spec:
  type: website
  lifecycle: production
  owner: group:admin-group 
  ownedBy: [group:ADMCOE-Team, group:admin-group, group:dev-group]
  dependsOn: []
  system: "frontend-team"

